// src/App.tsx
import React from 'react';
import './App.css';
import {Row, Col, Image}  from 'react-bootstrap';
import 'bootstrap/dist/css/bootstrap.min.css';

import mypic from './images/me.png';
import linkedinlogo from './images/linkedin-icon.png';
import resumeIcon from './images/resume-icon.png';
import resume from './resume.pdf';


function App() {
  return (
    <div className="App bg-dark text-white ">
        <Row>
          <Col><Image src={mypic} className="myPicture"></Image></Col>
          <Col>
              <h1>Peyton Howell</h1>
              <h3>About Me</h3>
              <p>Software Engineer | CS @ Georgia Tech, 2021</p>
              <p>Interested in software engineering opportunities</p>
              <div className="horizontalMargin">
                <a href="https://www.linkedin.com/in/peytonhowell/" className="horizontalMargin"><Image src={linkedinlogo} className="logo" aria-label="LinkedIn"></Image></a>
                <a href={resume} className="horizontalMargin"><Image src={resumeIcon} className="logo" aria-label="Resume"></Image> </a>        
              </div>
          </Col>
        </Row>
    </div>
  );
}

export default App;

// personalwebsite/src/app/app.component.ts
import { Component } from '@angular/core';
import { mdiLinkedin } from '@mdi/js';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'personalwebsite';
}

<head>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons&display=block" rel="stylesheet"> 
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.css">
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500&display=swap" rel="stylesheet">
</head>

<body>
  <h1 style="font-size:40px">Peyton Howell</h1>
  <br style="size: 20px;">
  <div class="row">
    <div class="column">
      <h2>About Me</h2>
      <p>I am a 2nd year computer science major at Georgia Tech. Interested in software engineering opportunities</p>  
    </div>
    <div class="column">
      <img src="../assets//profile picture.jpg">
    </div>
  </div>
  <div class="row" style="padding:20px">
    <a href="https://www.linkedin.com/in/peytonhowell/"><i class='fab fa-linkedin fa-2x white-icon'></i></a>
    <a href="../assets/resume.pdf"><mat-icon class="white-icon">file_copy</mat-icon> </a>
</div>

</body>
